### ISSUE TITLE
"Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"

### ISSUE THREAD

**Issue by fresheneesz** [simlrh/babel-webpack-plugin#1]
Trying to use this with the default options, but I'm getting this on build:

```
/home/vagrant/backend/node_modules/babel-webpack-plugin/index.js:7
class BabelPlugin {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/vagrant/backend/git/node_modules/webpacker.js:9:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by fresheneesz** [comment]
node v 5.1.0, webpack 3.6.0

**Comment by fresheneesz** [comment]
Seems I have to run a newer version of node to make this work. I need es6 in order to create es6? : / 

In any case, it works in node v6.11.3
